[build]
  command = "CI= npm run build" # the command you run to build this file
  functions = "built" # netlify builds to this folder AND Netlify reads functions from here
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically


[[redirects]]
from = "/*"
to = "https://restcountries.com/v3.1/all"
status = 200
headers = {X-From = "Netlify"}

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"